// สินค้าตัวอย่าง (พระเครื่อง) — ผูกกับ monkSlug/provinceSlug/categorySlug ที่มีอยู่แล้ว
// รูปใช้ placeholder (https://placehold.co) ตามแนวทาง dev ใน CLAUDE.md

export type ProductImageSeed = {
  url: string;
  type: "product" | "certificate";
};

export type ProductSeed = {
  name: string;
  description: string;
  costPrice: number;
  price: number;
  stock: number;
  monkSlug: string;
  provinceSlug: string;
  categorySlug: string;
  templeName: string;
  era: string;
  hasCertificate: boolean;
  certificateInfo?: string;
  images: ProductImageSeed[];
};

function placeholder(label: string, bg: string, fg = "ffffff") {
  return `https://placehold.co/600x600/${bg}/${fg}?text=${encodeURIComponent(label)}`;
}

export const products: ProductSeed[] = [
  {
    name: "เหรียญหลวงพ่อคูณ รุ่นเสาร์ห้า",
    description: "เหรียญรูปเหมือนหลวงพ่อคูณ ปริสุทฺโธ รุ่นเสาร์ห้า เนื้อทองแดงรมดำ สภาพสวยเดิมๆ",
    costPrice: 3500,
    price: 4800,
    stock: 3,
    monkSlug: "luang-pho-koon",
    provinceSlug: "nakhon-ratchasima",
    categorySlug: "rian-pum",
    templeName: "วัดบ้านไร่",
    era: "ปี 2536",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากร้าน ตรวจสอบย้อนกลับได้",
    images: [
      { url: placeholder("เหรียญหลวงพ่อคูณ", "8a5a2b"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "ล็อกเก็ตหลวงพ่อคูณ รุ่นกูให้รวย",
    description: "ล็อกเก็ตรูปหลวงพ่อคูณ รุ่นกูให้รวย ด้านหลังฝังตะกรุดเงิน",
    costPrice: 1200,
    price: 1800,
    stock: 5,
    monkSlug: "luang-pho-koon",
    provinceSlug: "nakhon-ratchasima",
    categorySlug: "locket",
    templeName: "วัดบ้านไร่",
    era: "ปี 2537",
    hasCertificate: false,
    images: [{ url: placeholder("ล็อกเก็ตหลวงพ่อคูณ", "8a5a2b"), type: "product" }],
  },
  {
    name: "พระหลวงปู่ทวด เนื้อว่าน พิมพ์ใหญ่",
    description: "พระหลวงปู่ทวด เนื้อว่าน วัดช้างให้ พิมพ์ใหญ่ ปี 2505 ผิวเดิม",
    costPrice: 45000,
    price: 65000,
    stock: 1,
    monkSlug: "luang-pu-thuat",
    provinceSlug: "pattani",
    categorySlug: "phra-phong",
    templeName: "วัดช้างให้",
    era: "ปี 2505",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากสมาคมผู้นิยมพระเครื่องพระบูชาไทย",
    images: [
      { url: placeholder("หลวงปู่ทวดพิมพ์ใหญ่", "1d5f4a"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "เหรียญหลวงปู่ทวด หลังเตารีด",
    description: "เหรียญหลวงปู่ทวด วัดช้างให้ รุ่นหลังเตารีด เนื้อทองแดง",
    costPrice: 180000,
    price: 250000,
    stock: 1,
    monkSlug: "luang-pu-thuat",
    provinceSlug: "pattani",
    categorySlug: "rian-pum",
    templeName: "วัดช้างให้",
    era: "ปี 2506",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากสมาคมผู้นิยมพระเครื่องพระบูชาไทย",
    images: [
      { url: placeholder("หลังเตารีด", "1d5f4a"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "พระสมเด็จวัดระฆัง พิมพ์ใหญ่",
    description: "พระสมเด็จวัดระฆังโฆสิตาราม พิมพ์ใหญ่ สร้างโดยสมเด็จพระพุฒาจารย์ (โต พรหมรังสี)",
    costPrice: 300000,
    price: 450000,
    stock: 1,
    monkSlug: "somdej-toh",
    provinceSlug: "bangkok",
    categorySlug: "phra-somdej",
    templeName: "วัดระฆังโฆสิตาราม",
    era: "กรุงเก่า",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากสมาคมผู้นิยมพระเครื่องพระบูชาไทย",
    images: [
      { url: placeholder("สมเด็จวัดระฆัง", "5a3a1a"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "พระสมเด็จวัดระฆัง พิมพ์เจดีย์",
    description: "พระสมเด็จวัดระฆังโฆสิตาราม พิมพ์เจดีย์ เนื้อผงเก่า",
    costPrice: 180000,
    price: 280000,
    stock: 1,
    monkSlug: "somdej-toh",
    provinceSlug: "bangkok",
    categorySlug: "phra-somdej",
    templeName: "วัดระฆังโฆสิตาราม",
    era: "กรุงเก่า",
    hasCertificate: false,
    images: [{ url: placeholder("พิมพ์เจดีย์", "5a3a1a"), type: "product" }],
  },
  {
    name: "พระรูปเหมือนหลวงพ่อเงิน วัดบางคลาน",
    description: "พระรูปเหมือนปั๊มหลวงพ่อเงิน พุทธโชติ เนื้อทองผสม",
    costPrice: 25000,
    price: 38000,
    stock: 2,
    monkSlug: "luang-pho-ngern",
    provinceSlug: "phichit",
    categorySlug: "rup-lo",
    templeName: "วัดบางคลาน",
    era: "ปี 2515",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากร้าน ตรวจสอบย้อนกลับได้",
    images: [
      { url: placeholder("หลวงพ่อเงิน", "6b4a2b"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "เหรียญหลวงปู่มั่น ภูริทัตโต รุ่นแรก",
    description: "เหรียญรุ่นแรกหลวงปู่มั่น ภูริทัตโต วัดป่าสุทธาวาส เนื้อทองแดง",
    costPrice: 60000,
    price: 85000,
    stock: 1,
    monkSlug: "luang-pu-mun",
    provinceSlug: "sakon-nakhon",
    categorySlug: "rian-pum",
    templeName: "วัดป่าสุทธาวาส",
    era: "ปี 2493",
    hasCertificate: false,
    images: [{ url: placeholder("หลวงปู่มั่นรุ่นแรก", "3a3a3a"), type: "product" }],
  },
  {
    name: "ตะกรุดหลวงพ่อเดิม วัดหนองโพ",
    description: "ตะกรุดเนื้อโลหะถักเชือกแดง ลงอักขระโดยหลวงพ่อเดิม พุทธสโร",
    costPrice: 8000,
    price: 12000,
    stock: 4,
    monkSlug: "luang-pho-derm",
    provinceSlug: "nakhon-sawan",
    categorySlug: "takrut",
    templeName: "วัดหนองโพ",
    era: "ก่อนปี 2494",
    hasCertificate: false,
    images: [{ url: placeholder("ตะกรุดหลวงพ่อเดิม", "4a4a4a"), type: "product" }],
  },
  {
    name: "ตะกรุดโทนหลวงปู่ศุข วัดปากคลองมะขามเฒ่า",
    description: "ตะกรุดโทนเนื้อตะกั่ว ลงยันต์โดยหลวงปู่ศุข เกสโร พระอาจารย์ของกรมหลวงชุมพรเขตอุดมศักดิ์",
    costPrice: 40000,
    price: 58000,
    stock: 1,
    monkSlug: "luang-pu-suk",
    provinceSlug: "chai-nat",
    categorySlug: "takrut",
    templeName: "วัดปากคลองมะขามเฒ่า",
    era: "รัชกาลที่ 5",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากสมาคมผู้นิยมพระเครื่องพระบูชาไทย",
    images: [
      { url: placeholder("ตะกรุดหลวงปู่ศุข", "4a4a4a"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "รูปเหมือนหลวงพ่อพรหม วัดช่องแค รุ่นแรก",
    description: "รูปเหมือนปั๊มหลวงพ่อพรหม ถาวโร รุ่นแรก เนื้อทองแดง",
    costPrice: 15000,
    price: 22000,
    stock: 2,
    monkSlug: "luang-pho-prohm",
    provinceSlug: "nakhon-sawan",
    categorySlug: "rup-lo",
    templeName: "วัดช่องแค",
    era: "ปี 2516",
    hasCertificate: false,
    images: [{ url: placeholder("หลวงพ่อพรหม", "6b4a2b"), type: "product" }],
  },
  {
    name: "เหรียญหลวงปู่หมุน รุ่นเสาร์ห้ามหาเศรษฐี",
    description: "เหรียญหลวงปู่หมุน ฐิตสีโล วัดบ้านจาน รุ่นเสาร์ห้ามหาเศรษฐี",
    costPrice: 5500,
    price: 7900,
    stock: 6,
    monkSlug: "luang-pu-mun-thitasilo",
    provinceSlug: "si-sa-ket",
    categorySlug: "rian-pum",
    templeName: "วัดบ้านจาน",
    era: "ปี 2543",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากร้าน ตรวจสอบย้อนกลับได้",
    images: [
      { url: placeholder("หลวงปู่หมุน", "8a5a2b"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "ตะกรุดหลวงพ่อกวย วัดโฆสิตาราม",
    description: "ตะกรุดเนื้อทองแดงถักเชือก ลงอักขระโดยหลวงพ่อกวย ชุตินฺธโร",
    costPrice: 9000,
    price: 13500,
    stock: 3,
    monkSlug: "luang-pho-guay",
    provinceSlug: "chai-nat",
    categorySlug: "takrut",
    templeName: "วัดโฆสิตาราม",
    era: "ปี 2515",
    hasCertificate: false,
    images: [{ url: placeholder("ตะกรุดหลวงพ่อกวย", "4a4a4a"), type: "product" }],
  },
  {
    name: "รูปเหมือนล่องหนหลวงพ่อกวย",
    description: "รูปเหมือนปั๊มลอยองค์หลวงพ่อกวย รุ่นล่องหน เนื้อทองผสม",
    costPrice: 22000,
    price: 32000,
    stock: 1,
    monkSlug: "luang-pho-guay",
    provinceSlug: "chai-nat",
    categorySlug: "rup-lo",
    templeName: "วัดโฆสิตาราม",
    era: "ปี 2519",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากสมาคมผู้นิยมพระเครื่องพระบูชาไทย",
    images: [
      { url: placeholder("หลวงพ่อกวยล่องหน", "6b4a2b"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "เหรียญหลวงพ่อสด วัดปากน้ำภาษีเจริญ",
    description: "เหรียญรูปเหมือนหลวงพ่อสด จนฺทสโร ผู้ค้นพบวิชาธรรมกาย",
    costPrice: 4200,
    price: 6000,
    stock: 5,
    monkSlug: "luang-pho-sod",
    provinceSlug: "bangkok",
    categorySlug: "rian-pum",
    templeName: "วัดปากน้ำภาษีเจริญ",
    era: "ปี 2500",
    hasCertificate: false,
    images: [{ url: placeholder("หลวงพ่อสด", "8a5a2b"), type: "product" }],
  },
  {
    name: "เหรียญครูบาศรีวิชัย รุ่นแรก วัดบ้านปาง",
    description: "เหรียญรุ่นแรกครูบาศรีวิชัย นักบุญแห่งล้านนา เนื้อทองแดง",
    costPrice: 35000,
    price: 52000,
    stock: 1,
    monkSlug: "kruba-srivichai",
    provinceSlug: "lamphun",
    categorySlug: "rian-pum",
    templeName: "วัดบ้านปาง",
    era: "ปี 2482",
    hasCertificate: true,
    certificateInfo: "มีใบรับประกันจากสมาคมผู้นิยมพระเครื่องพระบูชาไทย",
    images: [
      { url: placeholder("ครูบาศรีวิชัยรุ่นแรก", "1d5f4a"), type: "product" },
      { url: placeholder("ใบรับประกัน", "2b2118"), type: "certificate" },
    ],
  },
  {
    name: "ล็อกเก็ตครูบาศรีวิชัย",
    description: "ล็อกเก็ตรูปครูบาศรีวิชัย ด้านหลังบรรจุผงเก่าวัดบ้านปาง",
    costPrice: 1500,
    price: 2200,
    stock: 8,
    monkSlug: "kruba-srivichai",
    provinceSlug: "lamphun",
    categorySlug: "locket",
    templeName: "วัดบ้านปาง",
    era: "ปี 2535",
    hasCertificate: false,
    images: [{ url: placeholder("ล็อกเก็ตครูบาศรีวิชัย", "1d5f4a"), type: "product" }],
  },
];
